### ISSUE TITLE
In version 0.18.0, I am unable to read the cookie folder associated with the currently logged-in Chrome account. It throws a permission error.

### ISSUE THREAD

**Issue by zhaotong1121** [borisbabic/browser_cookie3#179] opened 2023-06-09 05:44 UTC
**Here is the exception stack trace information.**

Traceback (most recent call last):
  File "D:\PyCharm 2022.2.1\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code/pythonOfVue/generalTxt.py", line 120, in <module>
    get_cookie()
  File "D:/code/pythonOfVue/generalTxt.py", line 106, in get_cookie
    jc = browser_cookie3.chrome(domain_name=url)
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 973, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 387, in load
    con = _sqlite3_connect_readonly(self.cookie_file)
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 145, in _sqlite3_connect_readonly
    con = sqlite3.connect(uri + options, uri=True)
sqlite3.OperationalError: unable to open database file

**Comment by zhaotong1121** [comment] 2023-06-09 05:45
Traceback (most recent call last):
  File "D:\code\pythonOfVue\generalTxt.py", line 120, in <module>
    get_cookie()
  File "D:\code\pythonOfVue\generalTxt.py", line 106, in get_cookie
    jc = browser_cookie3.chrome(domain_name=url)
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 925, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 465, in __init__
    super().__init__(browser='Chrome', cookie_file=cookie_file, domain_name=domain_name, key_file=key_file, **args)
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 274, in __init__
    self.__add_key_and_cookie_file(**kwargs)
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 324, in __add_key_and_cookie_file
    self.tmp_cookie_file = _create_local_copy(cookie_file)
  File "C:\Users\zhaot\.virtualenvs\tradeCenterNx-kx4xaHRg\lib\site-packages\browser_cookie3\__init__.py", line 48, in _create_local_copy
    with open(tmp_cookie_file, "wb") as f1, open(cookie_file, "rb") as f2:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\zhaot\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Profile 4\\Network\\Cookies'

**Comment by darthwalsh** [comment] 2023-06-25 16:09
@zhaotong1121  maybe this should be closed as a duplicate of #180? (even though this issue was created first.)

If you can't manually make a copy of `%LOCALAPPDATA%\Google\Chrome\User Data\Default\Network\Cookies` file because chrome is open, it's the same root cause.

**Comment by rafiibrahim8** [comment] 2023-06-25 17:54
@darthwalsh Yeah. People are commenting on the other issue.

**Closed by rafiibrahim8** 2023-06-25 17:54 UTC
