### ISSUE TITLE
Not Working On Windows OS

### ISSUE THREAD

**Issue by Usercodersystem** [borisbabic/browser_cookie3#204] opened 2024-03-08 18:04 UTC
Hello I Have A permissionError after get cookie value From chrome.
![Uploading Screenshot_20240308_213039_Microsoft Remote Desktop.jpg…]()

**Comment by FeldrinH** [comment] 2024-05-25 00:45
The screenshot link is broken, but this is probably a duplicate of https://github.com/borisbabic/browser_cookie3/issues/180

**Closed** 2024-12-19 23:52 UTC

**Comment by Usercodersystem** [comment] 2025-02-02 09:53
@FeldrinH oh this js github bug🤣🤣
